### ISSUE TITLE
Branch maintenance policy

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/development#135]
The branches section on BitBucket has reached two pages. I believe some cleanup is due, especially for branches that have not seen any development during the current year.

Is there any branch you feel should be dropped for good?

**Comment by pietercollins** [comment]
I generally agree with removing dormant branches. 

I've been working with a system where we have a working- branch for each module, and short-term sub-branches for each issue. However, I'm also happy just with a single working branch and sub-branches from that. What do you think best?

**Comment by lgeretti** [comment]
I am quite open on that. I propose the following:

1) We maintain one branch per module, so that those branches never get removed
2) Any other branch we need shall explicitly sub-branch from those (and other branches may sub-branch from them, if required)
3) No one shall directly commit on working, if not for ultimately merging into master. If it works on working, then it can be safely merged into master. This means that working becomes the "new" pending, and pending is not necessary.

What do you think?

**Comment by lgeretti** [comment]
Any remaining use for cid and working-ssv branches?

I am also going to remove the long abandoned abstraction-refinement branch, too old to be resumed.

**Comment by lgeretti** [comment]
Agreed.
