### ISSUE TITLE
A new organization of tests

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/development#165]
I propose we improve the modularity when testing by separating tests into modules too.

This is not just for clarity and organization: I want to sensibly improve the test suite, increasing both the separation of concerns for single test files AND the amount of classes tested. Due to the NECESSARY increase in tests involved, a modularization is definitely due. By the way, after this change we can just issue "make test" within one module to simply run the tests in that module.

In addition, I want to introduce "secondary" tests, meaning tests that are not be part of the test suite from "make test" and are allowed not to pass. Those tests will reside in a secondary/ directory inside each module and will be run only when issuing a custom test command. The purpose of this approach is to consider tests that at most check for **desired** behavior, rather than **correct** behavior. An example is the current test_crossings_issue, which works correctly but produces a less-than-ideal set of trajectories: we could consider this result a failure since we do not like the outcome, but it is still correct so it shouldn't hinder the success of the test suite. We could say that these tests are for "improvements" rather than "bugs".

Additionally, secondary tests also allow us to expand the overall test suite without fear of slowing down "make test". Some tests that don't actually test anything but simply run the code shouldn't really be in the test suite: they are usually slow and they "don't know what they are doing". For example, evolution tests should be split into 1) very small tests that aim to check a specific behavior, and 2) large and long tests that simply try to touch incorrect execution paths, possibly relying on graphical output files for correctness checking.

**Comment by pietercollins** [comment]
Agree, especially with modularising tests.

**Comment by lgeretti** [comment]
Done.
