### ISSUE TITLE
All constructors of FloatXX should require precision

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/development#196]
All constructors of a FloatXX object should require a precision, including named constructors nan(...) and inf(...). This is to enforce consistency across Float classes.

**Comment by lgeretti** [comment]
Is this really necessary? I don't see any issues coming from the tests. 
On the other hand, that would be a problem for the fix I had in mind for construction of infinite/empty Interval and also to address #194. If you look into interval.inl.hpp:34,36,50 you see that we use FloatDP in all cases, but Real(FloatDP) is deprecated so an infinite/empty RealInterval would give the warning.

The ideal would be to have 
```c++
template<class U> Interval<U>::Interval(EmptyInterval const&) : Interval(L::inf(Sign::POSITIVE),U::inf(Sign::NEGATIVE)) { }
```

If we add precision this does not work in all cases.

Any suggestions? Can I provide two different implementations enabled in the presence of precision information?

**Comment by lgeretti** [comment]
Review the current working-python-#195 for a fix for both.
