### ISSUE TITLE
Symbolic representation in differential inclusion integrator 

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/development#218]
The DI integrator will be an extension of Integrator, and it does require a symbolic representation of the function for exact manipulation purposes. So I am essentially forced to provide a symbolic interface. This also suggests that, for consistency, an extension/wrapper of the other integrators that simply provides a symbolic interface should be offered. Do you agree?
_Originally posted by @lgeretti in https://github.com/ariadne-cps/development/issues/206#issuecomment-424279052_

**Comment by lgeretti** [comment]
Is this supposed to be the description of the task, or is it just the resuming of the discussion in a separate "thread"?

**Comment by pietercollins** [comment]
The basic integrator interface should work with general Validated functions, since the solution is well-defined for these, so we shouldn't require a Symbolic function in the interface.
If a solver requires more information, then we can define a method which uses this information, and implement the abstract interface using dynamical_cast to check whether the input provides this. I think this is best for now.
An alternative solution which is statically-typed would be to parametrise the interface on the input function type. However, I would like to think about the consequences of this approach before deciding to change the interfaces, especially as this will introduce more types.

For the inclusi
