### ISSUE TITLE
Infinite/NaN Integer/Dyadic/Rational values

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/development#70]
*Originally reported by* **Pieter Collins (Bitbucket: [pietercollins](https://bitbucket.org/pietercollins), GitHub: [pietercollins](https://github.com/pietercollins))**

----------------------------------------

Integer/Dyadic/Rational (and Real) numbers do not support infinite values, since they are based directly on GMP types, which do not support ∞. It would be very useful to support ±∞ and NaN for these values, as in many cases, templated code for the floating-point cases does not work for exact arithmetic e.g. upper/lower bounds on constraints. The semantics would be the same as for builtin floating-point numbers.

I see two possible ways of doing this: Either:

1. we support ±∞ and NaN in the Integer/Dyadic/Rational classes themselves, or 
2. we define an Extended<X> template which provides these values. 

The advantages of 2. are that we keep Integer/Dyadic/Rational with finite values (potentially avoiding needless checks) and that we keep these classes as a direct wrapper for GMP. The advantages of 1. are direct compatibility of Integer/Dyadic/Rational with FloatXX, and avoiding extra classes.

----------------------------------------
- Bitbucket: https://bitbucket.org/ariadne-cps/development/issue/70

**Comment by lgeretti** [comment]
Dyadic and Rational addressed as of 660e5ed6

**Comment by pietercollins** [comment]
I've implemented versions of Dyadic and Rational with internal inf and NaN values.

**Comment by lgeretti** [comment]
Isn't Integer still missing though?

**Comment by pietercollins** [comment]
Yes, Integer inf/NaN is missing. I need to think about how to represent the values in GMP. It's also not critical, since neither builtin ints nor mpz_t have inf/NaN, and we can't create an Integer inf/NaN by division since division returns a Rational.

Pieter
